# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_biomass_components <- function(plot, tree, fia_spp, division, vtotib, dbh, height) {
    .Call(`_nsvbR_compute_biomass_components`, plot, tree, fia_spp, division, vtotib, dbh, height)
}

